### ISSUE TITLE
Implement history with reverse search

### ISSUE THREAD

**Issue by jvorcak** [webscopeio/react-console#3]
The plan is to implement history & reverse search like in a regular console.

**Comment by jankoritak** [comment]
History proposal:

General:

- Controlled-component-like history API via a new prop

API:

- A single prop `history`
- `history` prop is of type `boolean | HistoryConfig`, where `HistoryConfig` is
```
interface HistoryConfig {
  history: Array<string>,
  onCommand: (string) => void, 
}
```

Spec:

- `history` prop contains ordered FIFO queue of previous commands
- `onCommand` callback is triggered on every command submission, passes the new command as an argument
